#!/bin/sh

hyprctl -i 0 dispatch togglespecialworkspace magic
hyprctl -i 0 dispatch movecursor 1000 700
sleep 0.2
hyprctl -i 0 dispatch exec 'kitty --hold sh -c "btop"'
sleep 0.2
hyprctl -i 0 dispatch exec 'kitty --hold sh -c "ncmpcpp"'
sleep 0.2
hyprctl -i 0 dispatch exec 'kitty --hold sh -c "nvtop"'
sleep 1
hyprctl -i 0 dispatch movefocus l
sleep 0.2
hyprctl -i 0 dispatch exec kitty
sleep 1
hyprctl -i 0 dispatch resizeactive 0 60

