#!/bin/sh

while true; do
clear
fastfetch --logo-type none
input=$(gum choose "Entry" "Networks" "SystemControlSpace Setup" "Shutdown Terminalctl")

case $input in 
    "Shutdown Terminalctl")
        clear
        echo ok
        break
        ;;
    "Networks")
        while true; do
        clear
        fastfetch --logo-type none
        input2=$(gum choose "<- back" "LIST" "CONNECT" "NAT" "IP FORWARD")
        case $input2 in 
            "LIST")
                nmcli device wifi list
                ;;
            "CONNECT")
                ;;
            "NAT")
                ;;
            "IP FORWARD")
                ;;
            "<- back")
                break
                ;;
        esac
        clear
        done
        ;;
esac
done
